---
deployment:
  tasks:
    - export DEPLOYPATH=/home/cp2639565p41/public_html
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -R .htaccess $DEPLOYPATH 2>/dev/null || true
    - mkdir -p $DEPLOYPATH/tmp
    - mkdir -p $DEPLOYPATH/staticfiles
    - mkdir -p $DEPLOYPATH/media
    - chmod -R 755 $DEPLOYPATH
    - touch $DEPLOYPATH/tmp/restart.txt