# Generated by Django 5.1 on 2025-07-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_staffcontribution_staffinternalmessage_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('donation', 'Don'), ('event', 'Événement'), ('participation', 'Participation'), ('contribution', 'Contribution Staff'), ('project', 'Projet'), ('other', 'Autre')], max_length=20)),
                ('related_id', models.IntegerField(blank=True, null=True)),
                ('related_model', models.CharField(blank=True, max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField(blank=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
