# Generated by Django 4.2.14 on 2025-10-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_impactpoint"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitorFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=100, verbose_name="Nom"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                ("opinion", models.TextField(verbose_name="Avis sur le site/projet")),
                (
                    "contribution_type",
                    models.CharField(
                        choices=[
                            ("ideas", "Partager des idées"),
                            ("member", "Devenir membre"),
                            ("volunteer", "Participer aux activités"),
                            ("donate", "Faire un don"),
                            ("partner", "Devenir partenaire"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Type de contribution souhaitée",
                    ),
                ),
                (
                    "contribution_details",
                    models.TextField(
                        blank=True, verbose_name="Détails de la contribution"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_contacted",
                    models.BooleanField(default=False, verbose_name="Contacté"),
                ),
                ("contacted_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, verbose_name="Notes internes")),
            ],
            options={
                "verbose_name": "Avis visiteur",
                "verbose_name_plural": "Avis visiteurs",
                "ordering": ["-created_at"],
            },
        ),
    ]
