# Generated by Django 4.2.14 on 2025-10-30 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_visitorfeedback"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="donation",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="event",
            name="is_public",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="donation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="donation",
            name="donor_email",
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="donation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("completed", "Complété"),
                    ("failed", "Échoué"),
                    ("refunded", "Remboursé"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="transaction_id",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("workshop", "Atelier"),
                    ("conference", "Conférence"),
                    ("competition", "Compétition"),
                    ("fundraising", "Collecte de fonds"),
                    ("volunteer", "Bénévolat"),
                    ("community", "Communautaire"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_featured",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("planning", "En planification"),
                    ("active", "Actif"),
                    ("completed", "Terminé"),
                    ("suspended", "Suspendu"),
                ],
                db_index=True,
                default="planning",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["is_active", "name"], name="main_catego_is_acti_157815_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["status", "-created_at"], name="main_donati_status_23b188_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["donor_email", "status"], name="main_donati_donor_e_0701a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["project", "status"], name="main_donati_project_04e9b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["is_active", "date"], name="main_event_is_acti_a615fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["event_type", "is_active"], name="main_event_event_t_78622a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["-date"], name="main_event_date_326fbe_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["status", "-created_at"], name="main_projec_status_965f87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["is_featured", "status"], name="main_projec_is_feat_f4c189_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["-created_at"], name="main_projec_created_1bf4c9_idx"
            ),
        ),
    ]
